on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: actions/setup-java@v2.5.0
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2.3.0
      with:
        flutter-version: '2.5.3'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --debug --split-per-abi
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.TOKEN }}
